// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: World.proto
// Protobuf C++ Version: 5.29.1

#include "World.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr WorldToClient_EnterRoom::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::int64_t{0}},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WorldToClient_EnterRoom::WorldToClient_EnterRoom(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WorldToClient_EnterRoomDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WorldToClient_EnterRoomDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorldToClient_EnterRoomDefaultTypeInternal() {}
  union {
    WorldToClient_EnterRoom _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorldToClient_EnterRoomDefaultTypeInternal _WorldToClient_EnterRoom_default_instance_;

inline constexpr WorldToClient_Chat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WorldToClient_Chat::WorldToClient_Chat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WorldToClient_ChatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WorldToClient_ChatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorldToClient_ChatDefaultTypeInternal() {}
  union {
    WorldToClient_Chat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorldToClient_ChatDefaultTypeInternal _WorldToClient_Chat_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_World_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_World_2eproto = nullptr;
const ::uint32_t
    TableStruct_World_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::proto::WorldToClient_EnterRoom, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::WorldToClient_EnterRoom, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::WorldToClient_EnterRoom, _impl_.success_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::proto::WorldToClient_Chat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::proto::WorldToClient_Chat, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::WorldToClient_Chat, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::proto::WorldToClient_EnterRoom)},
        {10, -1, -1, sizeof(::proto::WorldToClient_Chat)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::proto::_WorldToClient_EnterRoom_default_instance_._instance,
    &::proto::_WorldToClient_Chat_default_instance_._instance,
};
const char descriptor_table_protodef_World_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013World.proto\022\005proto\032\014Common.proto\"6\n\027Wo"
    "rldToClient_EnterRoom\022\n\n\002id\030\001 \001(\003\022\017\n\007suc"
    "cess\030\002 \001(\010\"1\n\022WorldToClient_Chat\022\n\n\002id\030\001"
    " \001(\003\022\017\n\007message\030\002 \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_World_2eproto_deps[1] =
    {
        &::descriptor_table_Common_2eproto,
};
static ::absl::once_flag descriptor_table_World_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_World_2eproto = {
    false,
    false,
    149,
    descriptor_table_protodef_World_2eproto,
    "World.proto",
    &descriptor_table_World_2eproto_once,
    descriptor_table_World_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_World_2eproto::offsets,
    file_level_enum_descriptors_World_2eproto,
    file_level_service_descriptors_World_2eproto,
};
namespace proto {
// ===================================================================

class WorldToClient_EnterRoom::_Internal {
 public:
};

WorldToClient_EnterRoom::WorldToClient_EnterRoom(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.WorldToClient_EnterRoom)
}
WorldToClient_EnterRoom::WorldToClient_EnterRoom(
    ::google::protobuf::Arena* arena, const WorldToClient_EnterRoom& from)
    : WorldToClient_EnterRoom(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE WorldToClient_EnterRoom::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void WorldToClient_EnterRoom::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::success_));
}
WorldToClient_EnterRoom::~WorldToClient_EnterRoom() {
  // @@protoc_insertion_point(destructor:proto.WorldToClient_EnterRoom)
  SharedDtor(*this);
}
inline void WorldToClient_EnterRoom::SharedDtor(MessageLite& self) {
  WorldToClient_EnterRoom& this_ = static_cast<WorldToClient_EnterRoom&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* WorldToClient_EnterRoom::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WorldToClient_EnterRoom(arena);
}
constexpr auto WorldToClient_EnterRoom::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WorldToClient_EnterRoom),
                                            alignof(WorldToClient_EnterRoom));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WorldToClient_EnterRoom::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WorldToClient_EnterRoom_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WorldToClient_EnterRoom::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WorldToClient_EnterRoom>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WorldToClient_EnterRoom::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WorldToClient_EnterRoom>(), &WorldToClient_EnterRoom::ByteSizeLong,
            &WorldToClient_EnterRoom::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_._cached_size_),
        false,
    },
    &WorldToClient_EnterRoom::kDescriptorMethods,
    &descriptor_table_World_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WorldToClient_EnterRoom::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> WorldToClient_EnterRoom::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::WorldToClient_EnterRoom>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WorldToClient_EnterRoom, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_.success_)}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WorldToClient_EnterRoom, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void WorldToClient_EnterRoom::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.WorldToClient_EnterRoom)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WorldToClient_EnterRoom::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WorldToClient_EnterRoom& this_ = static_cast<const WorldToClient_EnterRoom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WorldToClient_EnterRoom::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WorldToClient_EnterRoom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:proto.WorldToClient_EnterRoom)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // bool success = 2;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:proto.WorldToClient_EnterRoom)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WorldToClient_EnterRoom::ByteSizeLong(const MessageLite& base) {
          const WorldToClient_EnterRoom& this_ = static_cast<const WorldToClient_EnterRoom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WorldToClient_EnterRoom::ByteSizeLong() const {
          const WorldToClient_EnterRoom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:proto.WorldToClient_EnterRoom)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int64 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_id());
            }
            // bool success = 2;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WorldToClient_EnterRoom::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WorldToClient_EnterRoom*>(&to_msg);
  auto& from = static_cast<const WorldToClient_EnterRoom&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.WorldToClient_EnterRoom)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WorldToClient_EnterRoom::CopyFrom(const WorldToClient_EnterRoom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.WorldToClient_EnterRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorldToClient_EnterRoom::InternalSwap(WorldToClient_EnterRoom* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_.success_)
      + sizeof(WorldToClient_EnterRoom::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(WorldToClient_EnterRoom, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata WorldToClient_EnterRoom::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WorldToClient_Chat::_Internal {
 public:
};

WorldToClient_Chat::WorldToClient_Chat(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.WorldToClient_Chat)
}
inline PROTOBUF_NDEBUG_INLINE WorldToClient_Chat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::proto::WorldToClient_Chat& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

WorldToClient_Chat::WorldToClient_Chat(
    ::google::protobuf::Arena* arena,
    const WorldToClient_Chat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorldToClient_Chat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:proto.WorldToClient_Chat)
}
inline PROTOBUF_NDEBUG_INLINE WorldToClient_Chat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void WorldToClient_Chat::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
WorldToClient_Chat::~WorldToClient_Chat() {
  // @@protoc_insertion_point(destructor:proto.WorldToClient_Chat)
  SharedDtor(*this);
}
inline void WorldToClient_Chat::SharedDtor(MessageLite& self) {
  WorldToClient_Chat& this_ = static_cast<WorldToClient_Chat&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* WorldToClient_Chat::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WorldToClient_Chat(arena);
}
constexpr auto WorldToClient_Chat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WorldToClient_Chat),
                                            alignof(WorldToClient_Chat));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WorldToClient_Chat::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WorldToClient_Chat_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WorldToClient_Chat::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WorldToClient_Chat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WorldToClient_Chat::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WorldToClient_Chat>(), &WorldToClient_Chat::ByteSizeLong,
            &WorldToClient_Chat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WorldToClient_Chat, _impl_._cached_size_),
        false,
    },
    &WorldToClient_Chat::kDescriptorMethods,
    &descriptor_table_World_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WorldToClient_Chat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> WorldToClient_Chat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::WorldToClient_Chat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(WorldToClient_Chat, _impl_.message_)}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WorldToClient_Chat, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(WorldToClient_Chat, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(WorldToClient_Chat, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(WorldToClient_Chat, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\0\7\0\0\0\0\0"
    "proto.WorldToClient_Chat"
    "message"
  }},
};

PROTOBUF_NOINLINE void WorldToClient_Chat::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.WorldToClient_Chat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.id_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WorldToClient_Chat::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WorldToClient_Chat& this_ = static_cast<const WorldToClient_Chat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WorldToClient_Chat::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WorldToClient_Chat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:proto.WorldToClient_Chat)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.WorldToClient_Chat.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:proto.WorldToClient_Chat)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WorldToClient_Chat::ByteSizeLong(const MessageLite& base) {
          const WorldToClient_Chat& this_ = static_cast<const WorldToClient_Chat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WorldToClient_Chat::ByteSizeLong() const {
          const WorldToClient_Chat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:proto.WorldToClient_Chat)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int64 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WorldToClient_Chat::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WorldToClient_Chat*>(&to_msg);
  auto& from = static_cast<const WorldToClient_Chat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.WorldToClient_Chat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WorldToClient_Chat::CopyFrom(const WorldToClient_Chat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.WorldToClient_Chat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorldToClient_Chat::InternalSwap(WorldToClient_Chat* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata WorldToClient_Chat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_World_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
