// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Packet.proto
// Protobuf C++ Version: 5.29.1

#include "Packet.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PacketHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PacketHeader::PacketHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketHeaderDefaultTypeInternal() {}
  union {
    PacketHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;

inline constexpr Packet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        header_{nullptr},
        payload_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Packet::Packet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketDefaultTypeInternal() {}
  union {
    Packet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketDefaultTypeInternal _Packet_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Packet_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Packet_2eproto = nullptr;
const ::uint32_t
    TableStruct_Packet_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PacketHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::PacketHeader, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::Packet, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Packet, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Packet, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Packet, _impl_.header_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Packet, _impl_.payload_),
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::PacketHeader)},
        {9, 23, -1, sizeof(::Packet)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_PacketHeader_default_instance_._instance,
    &::_Packet_default_instance_._instance,
};
const char descriptor_table_protodef_Packet_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014Packet.proto\032\023ServerPayload.proto\032\023Cli"
    "entPayload.proto\"\034\n\014PacketHeader\022\014\n\004size"
    "\030\001 \001(\005\"\322\001\n\006Packet\022\035\n\006header\030\001 \001(\0132\r.Pack"
    "etHeader\022\'\n\rlogin_request\030\350\007 \001(\0132\r.Login"
    "RequestH\000\022)\n\016login_response\030\351\007 \001(\0132\016.Log"
    "inResponseH\000\022%\n\014chat_request\030\352\007 \001(\0132\014.Ch"
    "atRequestH\000\022#\n\013chat_notify\030\353\007 \001(\0132\013.Chat"
    "NotifyH\000B\t\n\007payloadb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Packet_2eproto_deps[2] =
    {
        &::descriptor_table_ClientPayload_2eproto,
        &::descriptor_table_ServerPayload_2eproto,
};
static ::absl::once_flag descriptor_table_Packet_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Packet_2eproto = {
    false,
    false,
    307,
    descriptor_table_protodef_Packet_2eproto,
    "Packet.proto",
    &descriptor_table_Packet_2eproto_once,
    descriptor_table_Packet_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_Packet_2eproto::offsets,
    file_level_enum_descriptors_Packet_2eproto,
    file_level_service_descriptors_Packet_2eproto,
};
// ===================================================================

class PacketHeader::_Internal {
 public:
};

PacketHeader::PacketHeader(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PacketHeader)
}
PacketHeader::PacketHeader(
    ::google::protobuf::Arena* arena, const PacketHeader& from)
    : PacketHeader(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PacketHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.size_ = {};
}
PacketHeader::~PacketHeader() {
  // @@protoc_insertion_point(destructor:PacketHeader)
  SharedDtor(*this);
}
inline void PacketHeader::SharedDtor(MessageLite& self) {
  PacketHeader& this_ = static_cast<PacketHeader&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PacketHeader::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PacketHeader(arena);
}
constexpr auto PacketHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PacketHeader),
                                            alignof(PacketHeader));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PacketHeader::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PacketHeader_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PacketHeader::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PacketHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PacketHeader::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PacketHeader>(), &PacketHeader::ByteSizeLong,
            &PacketHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_._cached_size_),
        false,
    },
    &PacketHeader::kDescriptorMethods,
    &descriptor_table_Packet_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PacketHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> PacketHeader::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PacketHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 size = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketHeader, _impl_.size_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 size = 1;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void PacketHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:PacketHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.size_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PacketHeader::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PacketHeader& this_ = static_cast<const PacketHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PacketHeader::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PacketHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:PacketHeader)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 size = 1;
          if (this_._internal_size() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_size(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:PacketHeader)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PacketHeader::ByteSizeLong(const MessageLite& base) {
          const PacketHeader& this_ = static_cast<const PacketHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PacketHeader::ByteSizeLong() const {
          const PacketHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:PacketHeader)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 size = 1;
            if (this_._internal_size() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_size());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PacketHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PacketHeader*>(&to_msg);
  auto& from = static_cast<const PacketHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PacketHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_size() != 0) {
    _this->_impl_.size_ = from._impl_.size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PacketHeader::CopyFrom(const PacketHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PacketHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PacketHeader::InternalSwap(PacketHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.size_, other->_impl_.size_);
}

::google::protobuf::Metadata PacketHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Packet::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Packet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Packet, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Packet, _impl_._oneof_case_);
};

void Packet::set_allocated_login_request(::LoginRequest* login_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (login_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(login_request)->GetArena();
    if (message_arena != submessage_arena) {
      login_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, login_request, submessage_arena);
    }
    set_has_login_request();
    _impl_.payload_.login_request_ = login_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.login_request)
}
void Packet::clear_login_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kLoginRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.login_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.login_request_);
    }
    clear_has_payload();
  }
}
void Packet::set_allocated_login_response(::LoginResponse* login_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (login_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(login_response)->GetArena();
    if (message_arena != submessage_arena) {
      login_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, login_response, submessage_arena);
    }
    set_has_login_response();
    _impl_.payload_.login_response_ = login_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.login_response)
}
void Packet::clear_login_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kLoginResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.login_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.login_response_);
    }
    clear_has_payload();
  }
}
void Packet::set_allocated_chat_request(::ChatRequest* chat_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (chat_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(chat_request)->GetArena();
    if (message_arena != submessage_arena) {
      chat_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, chat_request, submessage_arena);
    }
    set_has_chat_request();
    _impl_.payload_.chat_request_ = chat_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.chat_request)
}
void Packet::clear_chat_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kChatRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.chat_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.chat_request_);
    }
    clear_has_payload();
  }
}
void Packet::set_allocated_chat_notify(::ChatNotify* chat_notify) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (chat_notify) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(chat_notify)->GetArena();
    if (message_arena != submessage_arena) {
      chat_notify = ::google::protobuf::internal::GetOwnedMessage(message_arena, chat_notify, submessage_arena);
    }
    set_has_chat_notify();
    _impl_.payload_.chat_notify_ = chat_notify;
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.chat_notify)
}
void Packet::clear_chat_notify() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kChatNotify) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.chat_notify_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.chat_notify_);
    }
    clear_has_payload();
  }
}
Packet::Packet(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Packet)
}
inline PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Packet& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_{},
        _oneof_case_{from._oneof_case_[0]} {}

Packet::Packet(
    ::google::protobuf::Arena* arena,
    const Packet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Packet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::PacketHeader>(
                              arena, *from._impl_.header_)
                        : nullptr;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kLoginRequest:
        _impl_.payload_.login_request_ = ::google::protobuf::Message::CopyConstruct<::LoginRequest>(arena, *from._impl_.payload_.login_request_);
        break;
      case kLoginResponse:
        _impl_.payload_.login_response_ = ::google::protobuf::Message::CopyConstruct<::LoginResponse>(arena, *from._impl_.payload_.login_response_);
        break;
      case kChatRequest:
        _impl_.payload_.chat_request_ = ::google::protobuf::Message::CopyConstruct<::ChatRequest>(arena, *from._impl_.payload_.chat_request_);
        break;
      case kChatNotify:
        _impl_.payload_.chat_notify_ = ::google::protobuf::Message::CopyConstruct<::ChatNotify>(arena, *from._impl_.payload_.chat_notify_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Packet)
}
inline PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        payload_{},
        _oneof_case_{} {}

inline void Packet::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.header_ = {};
}
Packet::~Packet() {
  // @@protoc_insertion_point(destructor:Packet)
  SharedDtor(*this);
}
inline void Packet::SharedDtor(MessageLite& self) {
  Packet& this_ = static_cast<Packet&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.header_;
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void Packet::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:Packet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kLoginRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.login_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.login_request_);
      }
      break;
    }
    case kLoginResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.login_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.login_response_);
      }
      break;
    }
    case kChatRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.chat_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.chat_request_);
      }
      break;
    }
    case kChatNotify: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.chat_notify_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.chat_notify_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* Packet::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Packet(arena);
}
constexpr auto Packet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Packet),
                                            alignof(Packet));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Packet::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Packet_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Packet::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Packet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Packet::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Packet>(), &Packet::ByteSizeLong,
            &Packet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Packet, _impl_._cached_size_),
        false,
    },
    &Packet::kDescriptorMethods,
    &descriptor_table_Packet_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Packet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 5, 5, 0, 7> Packet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Packet, _impl_._has_bits_),
    0, // no _extensions_
    1003, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Packet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .PacketHeader header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.header_)}},
  }}, {{
    1000, 0, 1,
    65520, 1,
    65535, 65535
  }}, {{
    // .PacketHeader header = 1;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LoginRequest login_request = 1000;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.payload_.login_request_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .LoginResponse login_response = 1001;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.payload_.login_response_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ChatRequest chat_request = 1002;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.payload_.chat_request_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ChatNotify chat_notify = 1003;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.payload_.chat_notify_), _Internal::kOneofCaseOffset + 0, 4,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::PacketHeader>()},
    {::_pbi::TcParser::GetTable<::LoginRequest>()},
    {::_pbi::TcParser::GetTable<::LoginResponse>()},
    {::_pbi::TcParser::GetTable<::ChatRequest>()},
    {::_pbi::TcParser::GetTable<::ChatNotify>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Packet::Clear() {
// @@protoc_insertion_point(message_clear_start:Packet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.header_ != nullptr);
    _impl_.header_->Clear();
  }
  clear_payload();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Packet::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Packet::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Packet)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .PacketHeader header = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.header_, this_._impl_.header_->GetCachedSize(), target,
                stream);
          }

          switch (this_.payload_case()) {
            case kLoginRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1000, *this_._impl_.payload_.login_request_, this_._impl_.payload_.login_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kLoginResponse: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1001, *this_._impl_.payload_.login_response_, this_._impl_.payload_.login_response_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kChatRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1002, *this_._impl_.payload_.chat_request_, this_._impl_.payload_.chat_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kChatNotify: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1003, *this_._impl_.payload_.chat_notify_, this_._impl_.payload_.chat_notify_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Packet)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Packet::ByteSizeLong(const MessageLite& base) {
          const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Packet::ByteSizeLong() const {
          const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Packet)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .PacketHeader header = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.header_);
            }
          }
          switch (this_.payload_case()) {
            // .LoginRequest login_request = 1000;
            case kLoginRequest: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.login_request_);
              break;
            }
            // .LoginResponse login_response = 1001;
            case kLoginResponse: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.login_response_);
              break;
            }
            // .ChatRequest chat_request = 1002;
            case kChatRequest: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.chat_request_);
              break;
            }
            // .ChatNotify chat_notify = 1003;
            case kChatNotify: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.chat_notify_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Packet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Packet*>(&to_msg);
  auto& from = static_cast<const Packet&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Packet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.header_ != nullptr);
    if (_this->_impl_.header_ == nullptr) {
      _this->_impl_.header_ =
          ::google::protobuf::Message::CopyConstruct<::PacketHeader>(arena, *from._impl_.header_);
    } else {
      _this->_impl_.header_->MergeFrom(*from._impl_.header_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kLoginRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.login_request_ =
              ::google::protobuf::Message::CopyConstruct<::LoginRequest>(arena, *from._impl_.payload_.login_request_);
        } else {
          _this->_impl_.payload_.login_request_->MergeFrom(from._internal_login_request());
        }
        break;
      }
      case kLoginResponse: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.login_response_ =
              ::google::protobuf::Message::CopyConstruct<::LoginResponse>(arena, *from._impl_.payload_.login_response_);
        } else {
          _this->_impl_.payload_.login_response_->MergeFrom(from._internal_login_response());
        }
        break;
      }
      case kChatRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.chat_request_ =
              ::google::protobuf::Message::CopyConstruct<::ChatRequest>(arena, *from._impl_.payload_.chat_request_);
        } else {
          _this->_impl_.payload_.chat_request_->MergeFrom(from._internal_chat_request());
        }
        break;
      }
      case kChatNotify: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.chat_notify_ =
              ::google::protobuf::Message::CopyConstruct<::ChatNotify>(arena, *from._impl_.payload_.chat_notify_);
        } else {
          _this->_impl_.payload_.chat_notify_->MergeFrom(from._internal_chat_notify());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Packet::CopyFrom(const Packet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Packet::InternalSwap(Packet* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.header_, other->_impl_.header_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Packet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Packet_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
