// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_MESSAGEDATA_H_
#define FLATBUFFERS_GENERATED_COMMON_MESSAGEDATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace MessageData {

struct Player;
struct PlayerBuilder;

enum PlayerType : int8_t {
  PlayerType_None = 0,
  PlayerType_Knight = 1,
  PlayerType_Mage = 2,
  PlayerType_Archer = 3,
  PlayerType_MIN = PlayerType_None,
  PlayerType_MAX = PlayerType_Archer
};

inline const PlayerType (&EnumValuesPlayerType())[4] {
  static const PlayerType values[] = {
    PlayerType_None,
    PlayerType_Knight,
    PlayerType_Mage,
    PlayerType_Archer
  };
  return values;
}

inline const char * const *EnumNamesPlayerType() {
  static const char * const names[5] = {
    "None",
    "Knight",
    "Mage",
    "Archer",
    nullptr
  };
  return names;
}

inline const char *EnumNamePlayerType(PlayerType e) {
  if (::flatbuffers::IsOutRange(e, PlayerType_None, PlayerType_Archer)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPlayerType()[index];
}

struct Player FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_TYPE = 8
  };
  int64_t id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  MessageData::PlayerType type() const {
    return static_cast<MessageData::PlayerType>(GetField<int8_t>(VT_TYPE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct PlayerBuilder {
  typedef Player Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int64_t id) {
    fbb_.AddElement<int64_t>(Player::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Player::VT_NAME, name);
  }
  void add_type(MessageData::PlayerType type) {
    fbb_.AddElement<int8_t>(Player::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  explicit PlayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Player> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Player>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Player> CreatePlayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    MessageData::PlayerType type = MessageData::PlayerType_None) {
  PlayerBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_name(name);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Player> CreatePlayerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    const char *name = nullptr,
    MessageData::PlayerType type = MessageData::PlayerType_None) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return MessageData::CreatePlayer(
      _fbb,
      id,
      name__,
      type);
}

}  // namespace MessageData

#endif  // FLATBUFFERS_GENERATED_COMMON_MESSAGEDATA_H_
